import type { Command } from '../src/types';
import { COMMANDS } from '../src/commands';

export const HAPPY_PATH_COMMANDS: readonly Command[] = [
  COMMANDS.START_DISCOVERY,
  COMMANDS.FINISH_DISCOVERY,
  COMMANDS.FINISH_QUESTIONS,
  COMMANDS.PLAN_PROPOSED,
  COMMANDS.APPROVE_PLAN,
  COMMANDS.TESTS_DESIGNED,
  COMMANDS.TESTS_COMPLETE,
  COMMANDS.TESTS_PASS,
  COMMANDS.IMPLEMENTATION_COMPLETE,
  COMMANDS.VERIFICATION_PASS,
  COMMANDS.REVIEW_APPROVED,
  COMMANDS.APPROVE_REVIEW,
  COMMANDS.PR_MERGED,
];

export const UP_TO_REVIEW_COMMANDS: readonly Command[] = [
  COMMANDS.START_DISCOVERY,
  COMMANDS.FINISH_DISCOVERY,
  COMMANDS.FINISH_QUESTIONS,
  COMMANDS.PLAN_PROPOSED,
  COMMANDS.APPROVE_PLAN,
  COMMANDS.TESTS_DESIGNED,
  COMMANDS.TESTS_COMPLETE,
  COMMANDS.TESTS_PASS,
  COMMANDS.IMPLEMENTATION_COMPLETE,
  COMMANDS.VERIFICATION_PASS,
];
