import type { Phase } from './types';

export const PHASES = {
  TICKET_RECEIVED: 'TICKET_RECEIVED',
  DISCOVERY: 'DISCOVERY',
  QUESTIONS: 'QUESTIONS',
  PLAN: 'PLAN',
  PLAN_APPROVAL: 'PLAN_APPROVAL',
  TEST_DESIGN: 'TEST_DESIGN',
  TEST_IMPLEMENTATION: 'TEST_IMPLEMENTATION',
  TEST_VERIFICATION: 'TEST_VERIFICATION',
  IMPLEMENTATION: 'IMPLEMENTATION',
  VERIFICATION: 'VERIFICATION',
  REVIEW: 'REVIEW',
  REVIEW_APPROVAL: 'REVIEW_APPROVAL',
  PR_CREATED: 'PR_CREATED',
  PREPROD: 'PREPROD',
  HUMAN_INTERVENTION_REQUIRED: 'HUMAN_INTERVENTION_REQUIRED',
} as const;

export const TERMINAL_PHASES: ReadonlySet<Phase> = new Set([
  PHASES.PREPROD,
  PHASES.HUMAN_INTERVENTION_REQUIRED,
]);
